### ISSUE TITLE
header and header and addition data

### ISSUE THREAD

**Issue by mrosama** [cheezytony/vue-datatable#1]
how can i send header  like authorization  token     and some  addition data parameter

**Comment by cheezytony** [comment]
Hi, @mrosama I'm incredibly sorry for the very late response.

In order to use request headers on the component just simply add an ajaxHeader prop like so

`<datatable :ajax="true" :url="your_url" :ajaxHeaders="{contentType: 'application/json'}" :columns="your_columns" />`

That should solve your problem
